'use client'

import { createContext, useContext, useEffect, useState, type ReactNode } from 'react'

export type Language = 'fr' | 'en' | 'mg'

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>('en')
  const [mounted, setMounted] = useState(false)

  useEffect(() => {
    setMounted(true)
    const savedLanguage = localStorage.getItem('language') as Language | null
    if (savedLanguage && ['fr', 'en', 'mg'].includes(savedLanguage)) {
      setLanguageState(savedLanguage)
    }
  }, [])

  useEffect(() => {
    if (!mounted) return
    // Save to localStorage
    localStorage.setItem('language', language)
    // Update HTML lang attribute
    if (typeof document !== 'undefined') {
      document.documentElement.lang = language
      // Update document title
      const translations = getTranslations(language)
      document.title =
        translations['site.title'] ||
        'Radio Madagasikara ho an\'i Kristy - 102.4 FM RMK'
    }
  }, [language, mounted])

  const setLanguage = (lang: Language) => {
    setLanguageState(lang)
  }

  // Translation function
  const t = (key: string): string => {
    const translations = getTranslations(language)
    return translations[key] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}

// Translation mappings
function getTranslations(lang: Language): Record<string, string> {
  const translations: Record<Language, Record<string, string>> = {
    fr: {
      // Site Title
      'site.title': 'Radio Madagasikara ho an\'i Kristy - 102.4 FM RMK',
      
      // Navigation
      'nav.home': 'Accueil',
      'nav.about': 'À Propos',
      'nav.programs': 'Programmes',
      'nav.podcasts': 'Podcasts',
      'nav.team': 'Équipe',
      'nav.donate': 'Faire un don',
      'nav.community': 'Communauté',
      'nav.prayer': 'Prière',
      'nav.worship': 'Adoration',
      'nav.meetings': 'Réunions',
      'nav.learning': 'Apprentissage',
      'nav.resources': 'Ressources',
      'nav.blog': 'Blog',
      'nav.publications': 'Publications',
      'nav.media': 'Médias',
      'nav.directory': 'Annuaire',
      'nav.projects': 'Projets',
      'nav.contact': 'Contact',
      'ui.language': 'Langue',
      'ui.theme': 'Thème',
      'ui.darkMode': 'Mode sombre',
      'ui.lightMode': 'Mode clair',
      
      // Home Page
      'home.title': 'Unis par la foi, agissant pour la Nation.',
      'home.subtitle': 'Une plateforme numérique de premier plan rassemblant les acteurs chrétiens engagés dans la transformation spirituelle, morale et civique de la nation.',
      'home.joinPrayer': 'Rejoindre la Salle de Prière',
      'home.watchWorship': 'Regarder l\'Adoration',
      'home.explore': 'Explorer Notre Plateforme',
      'home.platformDesc': 'La plateforme favorise la communion, la collaboration et l\'action collective au service du bien commun, en lien avec Madagascar et sa diaspora.',
      'home.prayerRooms': 'Salles de Prière',
      'home.prayerRoomsDesc': 'Rejoignez des salles de prière virtuelles pour des demandes de prière textuelles et vocales',
      'home.meetingRooms': 'Salles de Réunion',
      'home.meetingRoomsDesc': 'Connectez-vous dans des réunions vidéo sécurisées avec cryptage de bout en bout',
      'home.microLearning': 'Micro-Apprentissage',
      'home.microLearningDesc': 'Apprenez avec des vidéos, des résumés IA et des quiz interactifs',
      'home.blogPublications': 'Blog et Publications',
      'home.blogPublicationsDesc': 'Lisez des articles de blog et accédez à des publications PDF avec des résumés IA',
      'home.mediaHub': 'Centre Médias',
      'home.mediaHubDesc': 'Regardez des vidéos, écoutez de la musique et profitez de podcasts',
      'home.worship': 'Adoration',
      'home.worshipDesc': 'Rejoignez des sessions d\'adoration en direct ou regardez des services enregistrés',
      'home.ready': 'Prêt à Commencer?',
      'home.readyDesc': 'Rejoignez notre communauté aujourd\'hui et découvrez la communion, l\'apprentissage et l\'adoration d\'une nouvelle manière',
      'home.signIn': 'Se Connecter',
      'home.signUp': 'S\'inscrire',
      
      // Prayer Rooms
      'prayer.title': 'Salles de Prière Virtuelles',
      'prayer.subtitle': 'Partagez vos demandes de prière et rejoignez d\'autres dans la prière. Filtrez par nation pour voir les prières de régions spécifiques.',
      'prayer.share': 'Partager une Demande de Prière',
      'prayer.titleLabel': 'Titre',
      'prayer.contentLabel': 'Demande de Prière',
      'prayer.nationLabel': 'Nation (Optionnel)',
      'prayer.nationPlaceholder': 'ex: USA, Nigeria, Inde',
      'prayer.submit': 'Soumettre la Demande de Prière',
      'prayer.submitting': 'Soumission...',
      'prayer.requests': 'Demandes de Prière',
      'prayer.noRequests': 'Aucune demande de prière pour le moment. Soyez le premier à partager!',
      'prayer.error': 'Erreur lors de la soumission',
      'prayer.pray': 'Prier',
      'prayer.alreadyPrayed': 'Déjà prié',
      'prayer.loginToPray': 'Connectez-vous pour prier',
      'prayer.answered': 'Exaucé',
      'prayer.markAnswered': 'Marquer comme exaucé',
      'prayer.markUnanswered': 'Marquer comme non exaucé',
      
      // Auth
      'auth.modalTitle': 'Connexion Requise',
      'auth.modalDescription': 'Veuillez vous connecter ou créer un compte pour partager une demande de prière.',
      'auth.loginRequired': 'Vous devez être connecté pour partager une demande de prière.',
      'auth.signIn': 'Se Connecter',
      'auth.signUp': 'S\'inscrire',
      'auth.signOut': 'Se Déconnecter',
      'auth.signInDescription': 'Connectez-vous à votre compte',
      'auth.signUpDescription': 'Créez un nouveau compte',
      'auth.email': 'Email',
      'auth.emailPlaceholder': 'votre@email.com',
      'auth.password': 'Mot de passe',
      'auth.passwordPlaceholder': '••••••••',
      'auth.confirmPassword': 'Confirmer le mot de passe',
      'auth.confirmPasswordPlaceholder': '••••••••',
      'auth.name': 'Nom',
      'auth.namePlaceholder': 'Votre nom',
      'auth.signingIn': 'Connexion...',
      'auth.creatingAccount': 'Création du compte...',
      'auth.noAccount': 'Vous n\'avez pas de compte?',
      'auth.haveAccount': 'Vous avez déjà un compte?',
      'auth.createAccount': 'Créer un compte',
      'auth.signInError': 'Erreur lors de la connexion',
      'auth.signUpError': 'Erreur lors de la création du compte',
      'auth.passwordMismatch': 'Les mots de passe ne correspondent pas',
      'auth.passwordTooShort': 'Le mot de passe doit contenir au moins 6 caractères',
      'auth.forgotPassword': 'Mot de passe oublié?',
      'auth.resetPassword': 'Réinitialiser le mot de passe',
      'auth.resetPasswordDescription': 'Entrez votre adresse email et nous vous enverrons un lien pour réinitialiser votre mot de passe.',
      'auth.passwordResetSent': 'Le lien de réinitialisation du mot de passe a été envoyé à votre adresse email.',
      'auth.sendResetLink': 'Envoyer le lien',
      'auth.backToSignIn': 'Retour à la connexion',
      'auth.sending': 'Envoi...',
      'auth.cancel': 'Annuler',
      'auth.passwordResetSuccess': 'Mot de passe réinitialisé !',
      'auth.passwordResetSuccessMessage': 'Votre mot de passe a été modifié avec succès. Vous allez être redirigé vers la page d\'accueil...',
      'auth.goToHome': 'Aller à la page d\'accueil',
      'auth.resetPasswordPageDescription': 'Entrez votre nouveau mot de passe',
      'auth.resetting': 'Réinitialisation...',
      'auth.invalidResetLink': 'Lien de réinitialisation invalide ou expiré',
      'auth.resetLinkError': 'Erreur lors de la vérification du lien',
      
      // Profile
      'profile.title': 'Mon Profil',
      'profile.subtitle': 'Gérez vos informations personnelles et vos paramètres de compte',
      'profile.personalInfo': 'Informations Personnelles',
      'profile.name': 'Nom',
      'profile.email': 'Email',
      'profile.bio': 'Biographie',
      'profile.bioPlaceholder': 'Une courte biographie...',
      'profile.description': 'Description',
      'profile.descriptionPlaceholder': 'Parlez-nous de vous...',
      'profile.dateOfBirth': 'Date de Naissance',
      'profile.gender': 'Genre',
      'profile.selectGender': 'Sélectionner un genre',
      'profile.genderMale': 'Homme',
      'profile.genderFemale': 'Femme',
      'profile.genderOther': 'Autre',
      'profile.genderPreferNotToSay': 'Préfère ne pas dire',
      'profile.country': 'Pays',
      'profile.city': 'Ville',
      'profile.profession': 'Profession',
      'profile.phone': 'Téléphone',
      'profile.website': 'Site Web',
      'profile.save': 'Enregistrer',
      'profile.saving': 'Enregistrement...',
      'profile.saveSuccess': 'Profil mis à jour avec succès!',
      'profile.saveError': 'Erreur lors de la sauvegarde du profil',
      'profile.loadError': 'Erreur lors du chargement du profil',
      'profile.changePassword': 'Changer le Mot de Passe',
      'profile.newPassword': 'Nouveau Mot de Passe',
      'profile.confirmPassword': 'Confirmer le Mot de Passe',
      'profile.updatePassword': 'Mettre à Jour le Mot de Passe',
      'profile.updating': 'Mise à jour...',
      'profile.passwordUpdateError': 'Erreur lors de la mise à jour du mot de passe',
      'profile.emailUpdateError': 'Erreur lors de la mise à jour de l\'email',
      'profile.cancel': 'Annuler',
      
      // Meetings
      'meetings.title': 'Salles de Réunion',
      'meetings.subtitle': 'Participez à des réunions vidéo sécurisées et cryptées de bout en bout, comprenant une salle de réunion principale et 11 salles spécialisées réparties en plusieurs catégories.',
      'meetings.largeRoom': 'Grande Salle de Réunion',
      'meetings.smallRooms': 'Petites Salles de Réunion',
      'meetings.join': 'Rejoindre la Réunion',
      'meetings.capacity': 'Capacité',
      'meetings.e2ee': 'E2EE Activé',
      'meetings.viewAll': 'Voir Tout',
      'meetings.allRooms': 'Toutes les Salles de Réunion',
      'meetings.largeRoomName': 'CORPS DU CHRIST',
      'meetings.smallRoomNames.prayer': 'Prière',
      'meetings.smallRoomNames.family': 'Famille',
      'meetings.smallRoomNames.communication': 'Communication',
      'meetings.smallRoomNames.praise': 'Louange',
      'meetings.smallRoomNames.business': 'Commerce (Économie)',
      'meetings.smallRoomNames.politics': 'Politique',
      'meetings.smallRoomNames.education': 'Éducation',
      'meetings.smallRoomNames.youth': 'Jeunesse',
      'meetings.smallRoomNames.technology': 'Technologie',
      'meetings.smallRoomNames.environment': 'Environnement',
      'meetings.smallRoomNames.peace': 'Paix',
      
      // Worship
      'worship.title': 'Adoration',
      'worship.subtitle': 'Rejoignez des sessions d\'adoration en direct ou regardez des services enregistrés. Filtrez par nation pour trouver l\'adoration de régions spécifiques.',
      
      // Learning
      'learning.title': 'Salles de Micro-Apprentissage',
      'learning.subtitle': 'Apprenez grâce à des vidéos, des résumés générés par IA et des quiz interactifs. Filtrez le contenu par nation.',
      
      // Blog
      'blog.title': 'Blog',
      'blog.subtitle': 'Lisez des articles de blog inspirants de notre communauté. Filtrez par nation pour voir le contenu de régions spécifiques.',
      
      // Publications
      'publications.title': 'Publications',
      'publications.subtitle': 'Accédez à des publications PDF avec des résumés générés par IA. Filtrez par nation pour trouver du contenu pertinent à votre région.',
      
      // Media
      'media.title': 'Centre Médias Chrétien',
      'media.subtitle': 'Regardez des vidéos, écoutez de la musique et profitez de podcasts. Filtrez par nation pour découvrir du contenu de régions spécifiques.',
      
      // Directory
      'directory.title': 'Annuaire',
      'directory.subtitle': 'Contenu de l\'annuaire à venir...',
      
      // Projects
      'projects.title': 'Vitrine de Projets',
      'projects.subtitle': 'Explorez les projets et initiatives de notre communauté. Filtrez par nation pour voir les projets de régions spécifiques.',
      
      // Common
      'common.filterByNation': 'Filtrer par Nation',
      'common.allNations': 'Toutes les Nations',
      'common.customNation': 'Nation personnalisée...',
      'common.clear': 'Effacer',
      'common.showing': 'Affichage du contenu pour',
      'common.loading': 'Chargement...',
      'common.back': 'Retour',
      'common.backTo': 'Retour à',
      'common.by': 'par',
      'common.notFound': 'Contenu introuvable',
      'common.noContent': 'Aucun contenu disponible pour le moment.',
      'common.backToList': '← Retour à la Liste',
      
      // Footer
      'footer.tagline': 'Unis par la foi, agissant pour la Nation. Une plateforme numérique de premier plan rassemblant les acteurs chrétiens engagés dans la transformation spirituelle, morale et civique de la nation.',
      'footer.community': 'Communauté',
      'footer.resources': 'Ressources',
      'footer.about': 'À Propos',
      'footer.rights': 'Tous droits réservés.',
      'footer.designedBy': 'Conçu par',
      'footer.prayerRooms': 'Prière',
      'footer.meetings': 'Réunions',
      'footer.worship': 'Adoration',
      'footer.learning': 'Apprentissage',
      'footer.blog': 'Blog',
      'footer.publications': 'Publications',
      'footer.media': 'Médias',
      'footer.directory': 'Annuaire',
      'footer.projects': 'Projets',
      'footer.aboutUs': 'À Propos de Nous',
      
      // Contact Page
      'contact.title': 'Contactez-Nous',
      'contact.subtitle': 'Vous avez des questions sur notre travail? Vous souhaitez collaborer avec nous? Ou simplement en savoir plus? Nous serions ravis de vous entendre. Contactez-nous via l\'un des canaux ci-dessous.',
      'contact.quickResponse': 'Réponse Rapide',
      'contact.multipleChannels': 'Plusieurs Canaux',
      'contact.contactInfo': 'Informations de Contact',
      'contact.contactInfoDesc': 'Choisissez le moyen le plus pratique de nous contacter. Nous sommes là pour vous aider et répondre à toutes vos questions sur notre mission et notre travail.',
      'contact.emailUs': 'Envoyez-nous un Email',
      'contact.emailUsDesc': 'Envoyez-nous un message à tout moment',
      'contact.callUs': 'Appelez-Nous',
      'contact.callUsDesc': 'Parlez directement avec notre équipe',
      'contact.visitUs': 'Visitez-Nous',
      'contact.visitUsDesc': 'Emplacement de notre bureau principal',
      'contact.sendMessage': 'Envoyez-nous un Message',
      'contact.sendMessageDesc': 'Remplissez le formulaire ci-dessous et nous vous répondrons dans les 24 heures. Pour les questions urgentes, veuillez nous appeler directement.',
      'contact.formName': 'Nom Complet',
      'contact.formNamePlaceholder': 'Votre nom complet',
      'contact.formEmail': 'Adresse Email',
      'contact.formEmailPlaceholder': 'votre@email.com',
      'contact.formSubject': 'Sujet',
      'contact.formSubjectPlaceholder': 'Sujet de votre message',
      'contact.formMessage': 'Message',
      'contact.formMessagePlaceholder': 'Votre message...',
      'contact.formSubmit': 'Envoyer le Message',
      'contact.formSubmitting': 'Envoi en cours...',
      'contact.formSuccess': 'Message envoyé avec succès! Nous vous répondrons dans les 24 heures.',
      'contact.formError': 'Erreur lors de l\'envoi du message. Veuillez réessayer.',
      'contact.formRequired': 'Champs obligatoires. Nous répondrons à votre message dans les 24 heures.',
      'contact.findUs': 'Trouvez-Nous',
      'contact.mainOffice': 'Notre Bureau Principal',
      'contact.getDirections': 'Obtenir l\'Itinéraire',
      'contact.responseTimes': 'Temps de Réponse',
      'contact.generalInquiries': 'Demandes Générales',
      'contact.generalInquiriesTime': 'Dans les 24 heures',
      'contact.partnershipInquiries': 'Demandes de Partenariat',
      'contact.partnershipInquiriesTime': 'Dans les 72 heures',
      'contact.emergencyContact': 'Contact d\'Urgence',
      'contact.emergencyContactTime': 'Immédiat',
      
      // About Page
      'about.intro': 'La Plateforme Numérique RNC – Refondation Nationale Chrétienne – est un espace numérique de premier plan conçu pour prolonger, structurer et renforcer l\'élan initié par la RNC sur le long terme. Elle vise à être un outil unificateur, collaboratif et stratégique, au service de tous les acteurs, participants et soutiens engagés dans la transformation spirituelle, morale et civique de la nation.',
      'about.mission': 'Notre Mission',
      'about.missionDesc': 'La mission principale de la plateforme numérique RNC est de créer un cadre numérique durable qui permettra de :',
      'about.mission1': 'Maintenir la communion, la coordination et la collaboration entre les acteurs de la RNC au-delà des rencontres et conférences occasionnelles',
      'about.mission2': 'Structurer l\'engagement collectif autour d\'une vision chrétienne de la transformation nationale',
      'about.mission3': 'Promouvoir la réflexion, la formation, l\'action concertée et la capacité à répondre aux grands défis du pays',
      'about.missionEnd': 'À travers cette plateforme, la RNC aspire à devenir un hub numérique d\'échange, de consultation, de formation et de mobilisation responsable.',
      'about.vision': 'Notre Vision',
      'about.visionDesc': 'Contribuer à l\'émergence d\'une nation renouvelée, fondée sur les valeurs chrétiennes, la responsabilité civique, l\'intégrité morale et le service du bien commun.',
      'about.visionEnd': 'Cette vision s\'inscrit dans une dynamique de renouvellement durable, où la foi, l\'engagement civique et l\'action collective se conjuguent pour construire un avenir plein d\'espoir.',
      'about.governance': 'Gouvernance Structurée et Inclusive',
      'about.governanceDesc': 'La plateforme numérique RNC s\'appuie sur une organisation claire et participative :',
      'about.circleZero': 'Le Cercle Zéro',
      'about.circleZeroDesc': 'Un organe d\'orientation stratégique et spirituelle, garantissant la vision, les valeurs et l\'éthique de la RNC',
      'about.coreTeam': 'L\'Équipe Centrale',
      'about.coreTeamDesc': 'Une équipe opérationnelle centrale responsable de la coordination globale, de la gestion de la plateforme et du suivi des actions',
      'about.thematicLeaders': 'Les 10 Leaders Thématiques',
      'about.thematicLeadersDesc': 'Facilitateurs des groupes thématiques, producteurs de contenu et porteurs de propositions et d\'actions',
      'about.regionalCommittees': 'Les Comités Régionaux RNC',
      'about.regionalCommitteesDesc': 'Représentants territoriaux responsables de la mobilisation locale, de la collecte des retours du terrain et de l\'organisation d\'activités au niveau régional',
      'about.platform': 'Une Plateforme au Service de l\'Action',
      'about.platformDesc': 'La plateforme numérique RNC met à disposition des outils modernes et sécurisés pour :',
      'about.platform1': 'Communauté et Réseau',
      'about.platform1a': 'Inscription et profils des membres (participants et soutiens)',
      'about.platform1b': 'Annuaire interne sécurisé',
      'about.platform1c': 'Mise en réseau par thème ou région',
      'about.platform2': 'Communication Interne',
      'about.platform2a': 'Messagerie interne',
      'about.platform2b': 'Espaces de discussion (forums, groupes thématiques, groupes régionaux)',
      'about.platform2c': 'Organisation de réunions en ligne (vidéoconférences)',
      'about.platform3': 'Information et Ressources',
      'about.platform3a': 'Actualités RNC et communiqués de presse officiels',
      'about.platform3b': 'Bibliothèque numérique (documents, rapports, déclarations, matériels RNC)',
      'about.platform3c': 'Calendrier des événements et réunions',
      'about.platform4': 'Formation et Renforcement des Capacités',
      'about.platform4a': 'Modules de formation en ligne (spirituel, leadership, citoyenneté, gouvernance, etc.)',
      'about.platform4b': 'Webinaires et enseignements vidéo',
      'about.platform4c': 'Espaces de discussion post-formation',
      'about.platform5': 'Organisation et Actions',
      'about.platform5a': 'Outils de coordination pour actions urgentes ou prioritaires',
      'about.platform5b': 'Mobilisation rapide des membres par thème ou zone',
      'about.platform5c': 'Suivi des initiatives et actions entreprises',
      'about.platform6': 'Gouvernance et Participation',
      'about.platform6a': 'Consultations internes',
      'about.platform6b': 'Enquêtes et prises de position collectives',
      'about.platform6c': 'Contributions des membres (propositions, réflexions, alertes)',
      'about.future': 'Une Approche Tournée vers l\'Avenir',
      'about.futureDesc': 'Conçue comme un outil évolutif, la plateforme numérique RNC est destinée à s\'ouvrir progressivement à un public plus large, à se connecter avec les églises, les organisations partenaires et la diaspora, et à intégrer de nouveaux services, notamment une application mobile et une archive des grandes déclarations nationales.',
    },
    en: {
      // Site Title
      'site.title': 'Radio Madagasikara ho an\'i Kristy - 102.4 FM RMK',
      
      // Navigation
      'nav.home': 'Home',
      'nav.about': 'About Us',
      'nav.programs': 'Programs',
      'nav.podcasts': 'Podcasts',
      'nav.team': 'Team',
      'nav.donate': 'Donate',
      'nav.community': 'Community',
      'nav.prayer': 'Prayer',
      'nav.worship': 'Worship',
      'nav.meetings': 'Meetings',
      'nav.learning': 'Learning',
      'nav.resources': 'Resources',
      'nav.blog': 'Blog',
      'nav.publications': 'Publications',
      'nav.media': 'Media',
      'nav.directory': 'Directory',
      'nav.projects': 'Projects',
      'nav.contact': 'Contact',
      'ui.language': 'Language',
      'ui.theme': 'Theme',
      'ui.darkMode': 'Dark mode',
      'ui.lightMode': 'Light mode',
      
      // Home Page
      'home.title': 'United by faith, Acting for the Nation.',
      'home.subtitle': 'A leading digital platform bringing together Christian actors committed to the spiritual, moral, and civic transformation of the nation.',
      'home.joinPrayer': 'Join Prayer Room',
      'home.watchWorship': 'Watch Worship',
      'home.explore': 'Explore Our Platform',
      'home.platformDesc': 'The platform fosters communion, collaboration, and collective action in service of the common good, in connection with Madagascar and its diaspora.',
      'home.prayerRooms': 'Prayer Rooms',
      'home.prayerRoomsDesc': 'Join virtual prayer rooms for text and voice prayer requests',
      'home.meetingRooms': 'Meeting Rooms',
      'home.meetingRoomsDesc': 'Connect in secure video meetings with end-to-end encryption',
      'home.microLearning': 'Micro-Learning',
      'home.microLearningDesc': 'Learn with videos, AI summaries, and interactive quizzes',
      'home.blogPublications': 'Blog & Publications',
      'home.blogPublicationsDesc': 'Read blog posts and access PDF publications with AI summaries',
      'home.mediaHub': 'Media Hub',
      'home.mediaHubDesc': 'Watch videos, listen to music, and enjoy podcasts',
      'home.worship': 'Worship',
      'home.worshipDesc': 'Join live worship sessions or watch recorded services',
      'home.ready': 'Ready to Get Started?',
      'home.readyDesc': 'Join our community today and experience fellowship, learning, and worship in a new way',
      'home.signIn': 'Sign In',
      'home.signUp': 'Sign Up',
      
      // Prayer Rooms
      'prayer.title': 'Virtual Prayer Rooms',
      'prayer.subtitle': 'Share your prayer requests and join others in prayer. Filter by nation to see prayers from specific regions.',
      'prayer.share': 'Share a Prayer Request',
      'prayer.titleLabel': 'Title',
      'prayer.contentLabel': 'Prayer Request',
      'prayer.nationLabel': 'Nation (Optional)',
      'prayer.nationPlaceholder': 'e.g., USA, Nigeria, India',
      'prayer.submit': 'Submit Prayer Request',
      'prayer.submitting': 'Submitting...',
      'prayer.requests': 'Prayer Requests',
      'prayer.noRequests': 'No prayer requests yet. Be the first to share!',
      'prayer.error': 'Error submitting prayer request',
      'prayer.pray': 'Pray',
      'prayer.alreadyPrayed': 'Already prayed',
      'prayer.loginToPray': 'Login to pray',
      'prayer.answered': 'Answered',
      'prayer.markAnswered': 'Mark as answered',
      'prayer.markUnanswered': 'Mark as unanswered',
      
      // Auth
      'auth.modalTitle': 'Login Required',
      'auth.modalDescription': 'Please sign in or create an account to share a prayer request.',
      'auth.loginRequired': 'You must be logged in to share a prayer request.',
      'auth.signIn': 'Sign In',
      'auth.signUp': 'Sign Up',
      'auth.signOut': 'Sign Out',
      'auth.signInDescription': 'Sign in to your account',
      'auth.signUpDescription': 'Create a new account',
      'auth.email': 'Email',
      'auth.emailPlaceholder': 'your@email.com',
      'auth.password': 'Password',
      'auth.passwordPlaceholder': '••••••••',
      'auth.confirmPassword': 'Confirm Password',
      'auth.confirmPasswordPlaceholder': '••••••••',
      'auth.name': 'Name',
      'auth.namePlaceholder': 'Your name',
      'auth.signingIn': 'Signing in...',
      'auth.creatingAccount': 'Creating account...',
      'auth.noAccount': 'Don\'t have an account?',
      'auth.haveAccount': 'Already have an account?',
      'auth.createAccount': 'Create an account',
      'auth.signInError': 'Error signing in',
      'auth.signUpError': 'Error creating account',
      'auth.passwordMismatch': 'Passwords do not match',
      'auth.passwordTooShort': 'Password must be at least 6 characters',
      'auth.forgotPassword': 'Forgot Password?',
      'auth.resetPassword': 'Reset Password',
      'auth.resetPasswordDescription': 'Enter your email address and we\'ll send you a link to reset your password.',
      'auth.passwordResetSent': 'Password reset link has been sent to your email address.',
      'auth.sendResetLink': 'Send Reset Link',
      'auth.backToSignIn': 'Back to Sign In',
      'auth.sending': 'Sending...',
      'auth.cancel': 'Cancel',
      'auth.passwordResetSuccess': 'Password Reset Successful!',
      'auth.passwordResetSuccessMessage': 'Your password has been successfully changed. You will be redirected to the home page...',
      'auth.goToHome': 'Go to Home Page',
      'auth.resetPasswordPageDescription': 'Enter your new password',
      'auth.resetting': 'Resetting...',
      'auth.invalidResetLink': 'Invalid or expired reset link',
      'auth.resetLinkError': 'Error verifying the reset link',
      
      // Profile
      'profile.title': 'My Profile',
      'profile.subtitle': 'Manage your personal information and account settings',
      'profile.personalInfo': 'Personal Information',
      'profile.name': 'Name',
      'profile.email': 'Email',
      'profile.bio': 'Bio',
      'profile.bioPlaceholder': 'A short bio...',
      'profile.description': 'Description',
      'profile.descriptionPlaceholder': 'Tell us about yourself...',
      'profile.dateOfBirth': 'Date of Birth',
      'profile.gender': 'Gender',
      'profile.selectGender': 'Select gender',
      'profile.genderMale': 'Male',
      'profile.genderFemale': 'Female',
      'profile.genderOther': 'Other',
      'profile.genderPreferNotToSay': 'Prefer not to say',
      'profile.country': 'Country',
      'profile.city': 'City',
      'profile.profession': 'Profession',
      'profile.phone': 'Phone',
      'profile.website': 'Website',
      'profile.save': 'Save',
      'profile.saving': 'Saving...',
      'profile.saveSuccess': 'Profile updated successfully!',
      'profile.saveError': 'Error saving profile',
      'profile.loadError': 'Error loading profile',
      'profile.changePassword': 'Change Password',
      'profile.newPassword': 'New Password',
      'profile.confirmPassword': 'Confirm Password',
      'profile.updatePassword': 'Update Password',
      'profile.updating': 'Updating...',
      'profile.passwordUpdateError': 'Error updating password',
      'profile.emailUpdateError': 'Error updating email',
      'profile.cancel': 'Cancel',
      
      // Learning
      'learning.quiz': 'Quiz',
      'learning.submitQuiz': 'Submit Quiz',
      'learning.quizResults': 'Quiz Results',
      'learning.correct': 'Correct',
      'learning.incorrect': 'Incorrect',
      'learning.score': 'You scored',
      'learning.outOf': 'out of',
      
      // Meetings
      'meetings.title': 'Meeting Rooms',
      'meetings.subtitle': 'Join secure, end-to-end encrypted video meetings featuring one main room and 11 specialized rooms across multiple categories.',
      'meetings.largeRoom': 'Large Meeting Room',
      'meetings.smallRooms': 'Small Meeting Rooms',
      'meetings.join': 'Join Meeting',
      'meetings.capacity': 'Capacity',
      'meetings.e2ee': 'E2EE Enabled',
      'meetings.viewAll': 'View All',
      'meetings.allRooms': 'All Meeting Rooms',
      'meetings.largeRoomName': 'BODY OF CHRIST',
      'meetings.smallRoomNames.prayer': 'Prayer',
      'meetings.smallRoomNames.family': 'Family',
      'meetings.smallRoomNames.communication': 'Communication',
      'meetings.smallRoomNames.praise': 'Praise',
      'meetings.smallRoomNames.business': 'Business (Economy)',
      'meetings.smallRoomNames.politics': 'Politics',
      'meetings.smallRoomNames.education': 'Education',
      'meetings.smallRoomNames.youth': 'Youth',
      'meetings.smallRoomNames.technology': 'Technology',
      'meetings.smallRoomNames.environment': 'Environment',
      'meetings.smallRoomNames.peace': 'Peace',
      
      // Worship
      'worship.title': 'Worship',
      'worship.subtitle': 'Join live worship sessions or watch recorded services. Filter by nation to find worship from specific regions.',
      
      // Learning
      'learning.title': 'Micro-Learning Rooms',
      'learning.subtitle': 'Learn through videos, AI-generated summaries, and interactive quizzes. Filter content by nation.',
      
      // Blog
      'blog.title': 'Blog',
      'blog.subtitle': 'Read inspiring blog posts from our community. Filter by nation to see content from specific regions.',
      
      // Publications
      'publications.title': 'Publications',
      'publications.subtitle': 'Access PDF publications with AI-generated summaries. Filter by nation to find content relevant to your region.',
      
      // Media
      'media.title': 'Christian Media Hub',
      'media.subtitle': 'Watch videos, listen to music, and enjoy podcasts. Filter by nation to discover content from specific regions.',
      
      // Directory
      'directory.title': 'Directory',
      'directory.subtitle': 'Directory content coming soon...',
      
      // Projects
      'projects.title': 'Project Showcase',
      'projects.subtitle': 'Explore projects and initiatives from our community. Filter by nation to see projects from specific regions.',
      
      // Common
      'common.filterByNation': 'Filter by Nation',
      'common.allNations': 'All Nations',
      'common.customNation': 'Custom nation...',
      'common.clear': 'Clear',
      'common.showing': 'Showing content for',
      'common.loading': 'Loading...',
      'common.back': 'Back',
      'common.backTo': 'Back to',
      'common.by': 'by',
      'common.notFound': 'Content not found',
      'common.noContent': 'No content available yet.',
      'common.backToList': '← Back to List',
      
      // Footer
      'footer.tagline': 'United by faith, Acting for the Nation. A leading digital platform bringing together Christian actors committed to the spiritual, moral, and civic transformation of the nation.',
      'footer.community': 'Community',
      'footer.resources': 'Resources',
      'footer.about': 'About',
      'footer.rights': 'All rights reserved.',
      'footer.designedBy': 'Designed by',
      'footer.prayerRooms': 'Prayer',
      'footer.meetings': 'Meetings',
      'footer.worship': 'Worship',
      'footer.learning': 'Learning',
      'footer.blog': 'Blog',
      'footer.publications': 'Publications',
      'footer.media': 'Media',
      'footer.directory': 'Directory',
      'footer.projects': 'Projects',
      'footer.aboutUs': 'About Us',
      
      // Contact Page
      'contact.title': 'Contact Us',
      'contact.subtitle': 'Have questions about our work? Want to partner with us? Or simply want to learn more? We\'d love to hear from you. Reach out to us through any of the channels below.',
      'contact.quickResponse': 'Quick Response',
      'contact.multipleChannels': 'Multiple Channels',
      'contact.contactInfo': 'Contact Information',
      'contact.contactInfoDesc': 'Choose the most convenient way to reach us. We\'re here to help and answer any questions you may have about our mission and work.',
      'contact.emailUs': 'Email Us',
      'contact.emailUsDesc': 'Send us a message anytime',
      'contact.callUs': 'Call Us',
      'contact.callUsDesc': 'Speak with our team directly',
      'contact.visitUs': 'Visit Us',
      'contact.visitUsDesc': 'Our main office location',
      'contact.sendMessage': 'Send us a Message',
      'contact.sendMessageDesc': 'Fill out the form below and we\'ll get back to you within 24 hours. For urgent matters, please call us directly.',
      'contact.formName': 'Full Name',
      'contact.formNamePlaceholder': 'Your full name',
      'contact.formEmail': 'Email Address',
      'contact.formEmailPlaceholder': 'your@email.com',
      'contact.formSubject': 'Subject',
      'contact.formSubjectPlaceholder': 'Subject of your message',
      'contact.formMessage': 'Message',
      'contact.formMessagePlaceholder': 'Your message...',
      'contact.formSubmit': 'Send Message',
      'contact.formSubmitting': 'Sending...',
      'contact.formSuccess': 'Message sent successfully! We\'ll respond to your message within 24 hours.',
      'contact.formError': 'Error sending message. Please try again.',
      'contact.formRequired': '* Required fields. We\'ll respond to your message within 24 hours.',
      'contact.findUs': 'Find Us',
      'contact.mainOffice': 'Our Main Office',
      'contact.getDirections': 'Get Directions',
      'contact.responseTimes': 'Response Times',
      'contact.generalInquiries': 'General Inquiries',
      'contact.generalInquiriesTime': 'Within 24 hours',
      'contact.partnershipInquiries': 'Partnership Inquiries',
      'contact.partnershipInquiriesTime': 'Within 72 hours',
      'contact.emergencyContact': 'Emergency Contact',
      'contact.emergencyContactTime': 'Immediate',
      
      // About Page
      'about.intro': 'The NCR Digital Platform – National Christian Refoundation – is a leading digital space designed to extend, structure, and strengthen the momentum initiated by the NCR over the long term. It aims to be a unifying, collaborative, and strategic tool, serving all stakeholders, participants, and supporters committed to the spiritual, moral, and civic transformation of the nation.',
      'about.mission': 'Our Mission',
      'about.missionDesc': 'The primary mission of the NCR digital platform is to create a sustainable digital framework that will:',
      'about.mission1': 'Maintain communion, coordination, and collaboration among NCR stakeholders beyond occasional meetings and conferences',
      'about.mission2': 'Structuring collective engagement around a Christian vision of national transformation',
      'about.mission3': 'Promoting reflection, training, concerted action, and the capacity to respond to the country\'s major challenges',
      'about.missionEnd': 'Through this platform, the NCR aspires to become a digital hub for exchange, consultation, training, and responsible mobilization.',
      'about.vision': 'Our Vision',
      'about.visionDesc': 'To contribute to the emergence of a renewed nation, founded on Christian values, civic responsibility, moral integrity, and service to the common good.',
      'about.visionEnd': 'This vision is part of a dynamic of sustainable renewal, where faith, civic engagement, and collective action combine to build a future full of hope.',
      'about.governance': 'Structured and Inclusive Governance',
      'about.governanceDesc': 'The NCR digital platform is based on a clear and participatory organization:',
      'about.circleZero': 'The Zero Circle',
      'about.circleZeroDesc': 'A strategic and spiritual guidance body, ensuring the vision, values, and ethics of the NCR',
      'about.coreTeam': 'The Core Team',
      'about.coreTeamDesc': 'A central operational team responsible for overall coordination, platform management, and action monitoring',
      'about.thematicLeaders': 'The 10 Thematic Leaders',
      'about.thematicLeadersDesc': 'Facilitators of the thematic groups, content producers, and proponents of proposals and actions',
      'about.regionalCommittees': 'The NCR Regional Committees',
      'about.regionalCommitteesDesc': 'Territorial representatives responsible for local mobilization, gathering feedback from the field, and organizing activities at the regional level',
      'about.platform': 'A Platform Serving Action',
      'about.platformDesc': 'The NCR digital platform provides modern and secure tools to:',
      'about.platform1': 'Community and Network',
      'about.platform1a': 'Member registration and profiles (participants and supporters)',
      'about.platform1b': 'Secure internal directory',
      'about.platform1c': 'Networking by theme or region',
      'about.platform2': 'Internal Communication',
      'about.platform2a': 'Internal messaging',
      'about.platform2b': 'Discussion spaces (forums, thematic groups, regional groups)',
      'about.platform2c': 'Organization of online meetings (videoconferences)',
      'about.platform3': 'Information and Resources',
      'about.platform3a': 'NCR news and official press releases',
      'about.platform3b': 'Digital library (documents, reports, statements, NCR materials)',
      'about.platform3c': 'Calendar of events and meetings',
      'about.platform4': 'Training and Capacity Building',
      'about.platform4a': 'Online training modules (spiritual, leadership, citizenship, governance, etc.)',
      'about.platform4b': 'Webinars and video teachings',
      'about.platform4c': 'Post-training discussion spaces',
      'about.platform5': 'Organization and Actions',
      'about.platform5a': 'Coordination tools for urgent or priority actions',
      'about.platform5b': 'Rapid mobilization of members by theme or area',
      'about.platform5c': 'Monitoring of initiatives and actions undertaken',
      'about.platform6': 'Governance and Participation',
      'about.platform6a': 'Internal Consultations',
      'about.platform6b': 'Surveys and Collective Position Papers',
      'about.platform6c': 'Member Contributions (Proposals, Reflections, Alerts)',
      'about.future': 'A Forward-Looking Approach',
      'about.futureDesc': 'Designed as an evolving tool, the NCR digital platform is intended to gradually open to a wider audience, connect with churches, partner organizations, and the diaspora, and integrate new services, including a mobile application and an archive of major national declarations.',
    },
    mg: {
      // Site Title
      'site.title': 'Radio Madagasikara ho an\'i Kristy - 102.4 FM RMK',
      
      // Navigation
      'nav.home': 'Fandraisana',
      'nav.about': 'Momba',
      'nav.programs': 'Fandaharana',
      'nav.podcasts': 'Podcast',
      'nav.team': 'Ekipa',
      'nav.donate': 'Fanomezana',
      'nav.community': 'Fiarahamonina',
      'nav.prayer': 'Fivavahana',
      'nav.worship': 'Fiderana',
      'nav.meetings': 'Fivoriana',
      'nav.learning': 'Fampianarana',
      'nav.resources': 'Fanànana',
      'nav.blog': 'Blog',
      'nav.publications': 'Famoahana',
      'nav.media': 'Haino',
      'nav.directory': 'Lisitra',
      'nav.projects': 'Tetikasa',
      'nav.contact': 'Fifandraisana',
      'ui.language': 'Fiteny',
      'ui.theme': 'Endrika',
      'ui.darkMode': 'Haizina',
      'ui.lightMode': 'Mazava',
      
      // Home Page
      'home.title': 'Tafaray amin\'ny finoana, miasa ho an\'ny Firenena.',
      'home.subtitle': 'Sehetra nomerika voalohany mampiray ny mpandray anjara kristiana miady amin\'ny fanovana ara-panahy, ara-moraly ary ara-panjakana amin\'ny firenena.',
      'home.joinPrayer': 'Miaraka Amin\'ny Efitra Fivavahana',
      'home.watchWorship': 'Mijery Fivavahana',
      'home.explore': 'Zahao Ny Sehatra',
      'home.platformDesc': 'Ny sehetra dia mampiroborobo ny firaisankina, ny fiaraha-miasa, ary ny hetsika miaraka amin\'ny fanompoana ny tombontsoa iraisana, mifandray amin\'i Madagasikara sy ny diaspora.',
      'home.prayerRooms': 'Efitra Fivavahana',
      'home.prayerRoomsDesc': 'Miaraka amin\'ny efitra fivavahana virtual ho an\'ny fangatahana vavaka amin\'ny teny sy feo',
      'home.meetingRooms': 'Efitra Fivoriana',
      'home.meetingRoomsDesc': 'Mifandray amin\'ny fivoriana video azo antoka miaraka amin\'ny fanafenana',
      'home.microLearning': 'Fampianarana Kely',
      'home.microLearningDesc': 'Mianatra amin\'ny lahatsary, famintinana AI, ary fanontaniana mifampiresaka',
      'home.blogPublications': 'Blog sy Famoahana',
      'home.blogPublicationsDesc': 'Vakio lahatsoratra blog ary fidirana amin\'ny famoahana PDF miaraka amin\'ny famintinana AI',
      'home.mediaHub': 'Foiben\'ny Haino',
      'home.mediaHubDesc': 'Mijery lahatsary, mihaino mozika ary mifaly amin\'ny podcast',
      'home.worship': 'Fivavahana',
      'home.worshipDesc': 'Miaraka amin\'ny fivavahana velona na mijery fivavahana voarakitra',
      'home.ready': 'Vonona hanomboka?',
      'home.readyDesc': 'Miaraka amin\'ny fiarahamonina ankehitriny ary mahafantatra ny fiaraha-miasa, fampianarana, ary fivavahana amin\'ny fomba vaovao',
      'home.signIn': 'Hiditra',
      'home.signUp': 'Hisoratra anarana',
      
      // Prayer Rooms
      'prayer.title': 'Efitra Fivavahana',
      'prayer.subtitle': 'Zarao ny fangatahana vavakao ary miaraka amin\'ny hafa amin\'ny vavaka. Sivana amin\'ny firenena mba hijery vavaka avy amin\'ny faritra manokana.',
      'prayer.share': 'Zarao Fangatahana Vavaka',
      'prayer.titleLabel': 'Lohateny',
      'prayer.contentLabel': 'Fangatahana Vavaka',
      'prayer.nationLabel': 'Firenena (Tsy Voatery)',
      'prayer.nationPlaceholder': 'ohatra: USA, Nigeria, India',
      'prayer.submit': 'Alefa Fangatahana Vavaka',
      'prayer.submitting': 'Ampidirina...',
      'prayer.requests': 'Fangatahana Vavaka',
      'prayer.noRequests': 'Tsy misy fangatahana vavaka mbola. Ianao no voalohany mizara!',
      'prayer.error': 'Diso ny fampidirana',
      'prayer.pray': 'Mivavaka',
      'prayer.alreadyPrayed': 'Efa nivavaka',
      'prayer.loginToPray': 'Midira mba hivavaka',
      'prayer.answered': 'Voavaly',
      'prayer.markAnswered': 'Marika ho voavaly',
      'prayer.markUnanswered': 'Marika ho tsy voavaly',
      
      // Auth
      'auth.modalTitle': 'Mila Hiditra',
      'auth.modalDescription': 'Midira na mamorona kaonty mba hizara fangatahana vavaka.',
      'auth.loginRequired': 'Tsy maintsy midira ianao mba hizara fangatahana vavaka.',
      'auth.signIn': 'Hiditra',
      'auth.signUp': 'Hisoratra anarana',
      'auth.signOut': 'Hivoaka',
      'auth.signInDescription': 'Hiditra amin\'ny kaontinao',
      'auth.signUpDescription': 'Mamorona kaonty vaovao',
      'auth.email': 'Email',
      'auth.emailPlaceholder': 'ny@email.com',
      'auth.password': 'Tenimiafina',
      'auth.passwordPlaceholder': '••••••••',
      'auth.confirmPassword': 'Hamafina ny tenimiafina',
      'auth.confirmPasswordPlaceholder': '••••••••',
      'auth.name': 'Anarana',
      'auth.namePlaceholder': 'Ny anaranao',
      'auth.signingIn': 'Miditra...',
      'auth.creatingAccount': 'Mamorona kaonty...',
      'auth.noAccount': 'Tsy manana kaonty?',
      'auth.haveAccount': 'Efa manana kaonty?',
      'auth.createAccount': 'Mamorona kaonty',
      'auth.signInError': 'Diso ny fidirana',
      'auth.signUpError': 'Diso ny famoronana kaonty',
      'auth.passwordMismatch': 'Tsy mitovy ny tenimiafina',
      'auth.passwordTooShort': 'Ny tenimiafina dia tsy maintsy misy farafahakeliny 6 tarehin-tsoratra',
      'auth.forgotPassword': 'Hadino ny tenimiafina?',
      'auth.resetPassword': 'Averina ny tenimiafina',
      'auth.resetPasswordDescription': 'Ampidiro ny adiresy mailakao ary hanaovantsika rohy iray hanavaozana ny tenimiafininao.',
      'auth.passwordResetSent': 'Nalefa ny rohy hanavaozana ny tenimiafina tamin\'ny adiresy mailakao.',
      'auth.sendResetLink': 'Alefa ny rohy',
      'auth.backToSignIn': 'Hiverina amin\'ny fidirana',
      'auth.sending': 'Alefa...',
      'auth.cancel': 'Ajanona',
      'auth.passwordResetSuccess': 'Nohavaozina ny tenimiafina!',
      'auth.passwordResetSuccessMessage': 'Nohavaozina soa aman-tsara ny tenimiafininao. Ho entina any amin\'ny pejy fandraisana ianao...',
      'auth.goToHome': 'Mandeha any amin\'ny pejy fandraisana',
      'auth.resetPasswordPageDescription': 'Ampidiro ny tenimiafinao vaovao',
      'auth.resetting': 'Averina...',
      'auth.invalidResetLink': 'Tsy manan-kery na lany daty ny rohy hanavaozana',
      'auth.resetLinkError': 'Diso ny fanamarinana ny rohy',
      
      // Profile
      'profile.title': 'Ny kaontiko',
      'profile.subtitle': 'Ny mombamomba anao manokana sy ny fikirana ao amin\'ny kaontinao',
      'profile.personalInfo': 'Momba anao manokana',
      'profile.name': 'Anarana',
      'profile.email': 'Mailaka',
      'profile.bio': 'Bio',
      'profile.bioPlaceholder': 'Bio fohy...',
      'profile.description': 'Famaritana',
      'profile.descriptionPlaceholder': 'Lazao anay ny momba anao...',
      'profile.dateOfBirth': 'Daty nahaterahana',
      'profile.gender': 'Lahy sa Vavy',
      'profile.selectGender': 'Misafidiana lahy sa Vavy',
      'profile.genderMale': 'Lehilahy',
      'profile.genderFemale': 'Vehivavy',
      'profile.genderOther': 'Hafa',
      'profile.genderPreferNotToSay': 'Aleoko tsy miteny',
      'profile.country': 'Firenena',
      'profile.city': 'Tanàna',
      'profile.profession': 'Asa',
      'profile.phone': 'Finday',
      'profile.website': 'Tranonkala',
      'profile.save': 'Tehirizo',
      'profile.saving': 'Tehirizina...',
      'profile.saveSuccess': 'Nohavaozina soa aman-tsara ny mombamomba!',
      'profile.saveError': 'Hadisoana teo amin\'ny fitahirizana ny mombamomba',
      'profile.loadError': 'Hadisoana teo amin\'ny famoahana ny mombamomba',
      'profile.changePassword': 'Hanova ny tenimiafina',
      'profile.newPassword': 'Tenimiafina vaovao',
      'profile.confirmPassword': 'Hamarino ny tenimiafina',
      'profile.updatePassword': 'Havaozy ny tenimiafina',
      'profile.updating': 'Fanavaozana...',
      'profile.passwordUpdateError': 'Hadisoana teo amin\'ny fanavaozana ny tenimiafina',
      'profile.emailUpdateError': 'Hadisoana teo am-panavaozana ny mailaka',
      'profile.cancel': 'Manafoana',
      
      // Learning
      'learning.quiz': 'Fanontaniana',
      'learning.submitQuiz': 'Alefa ny Valiny',
      'learning.quizResults': 'Vokatra Fanontaniana',
      'learning.correct': 'Marina',
      'learning.incorrect': 'Diso',
      'learning.score': 'Nahazo ianao',
      'learning.outOf': 'amin\'ny',
      
      // Meetings
      'meetings.title': 'Efitra Fivoriana',
      'meetings.subtitle': 'Mandraisa anjara amin\'ny fivoriana an-dahatsary azo antoka sy voaaro tanteraka, anisan\'izany ny efitrano fivoriana lehibe sy efitrano voatokana 11 mizara ho sokajy maromaro.',
      'meetings.largeRoom': 'Efitra Fivoriana Lehibe',
      'meetings.smallRooms': 'Efitra Fivoriana Kely',
      'meetings.join': 'Miaraka Amin\'ny Fivoriana',
      'meetings.capacity': 'Fahafahana',
      'meetings.e2ee': 'E2EE Miasa',
      'meetings.viewAll': 'Jereo Ny Rehetra',
      'meetings.allRooms': 'Efitra Fivoriana Rehetra',
      'meetings.largeRoomName': 'TENAN\'I KRISTY',
      'meetings.smallRoomNames.prayer': 'Fivavahana',
      'meetings.smallRoomNames.family': 'Fianakaviana',
      'meetings.smallRoomNames.communication': 'Serasera',
      'meetings.smallRoomNames.praise': 'Fiderana',
      'meetings.smallRoomNames.business': 'Fandraharahana (Toekarena)',
      'meetings.smallRoomNames.politics': 'Politika',
      'meetings.smallRoomNames.education': 'Fanabeazana',
      'meetings.smallRoomNames.youth': 'Tanora',
      'meetings.smallRoomNames.technology': 'Teknolojia',
      'meetings.smallRoomNames.environment': 'Tontolo iainana',
      'meetings.smallRoomNames.peace': 'Fandriam-pahalemana',
      
      // Worship
      'worship.title': 'Fiderana',
      'worship.subtitle': 'Miaraka amin\'ny fiderana mivantana na mijery ny efa voarakitra. Sivana amin\'ny firenena mba hahitana fiderana avy amin\'ny faritra manokana.',
      
      // Learning
      'learning.title': 'Efitra Fampianarana Kely',
      'learning.subtitle': 'Mianatra amin\'ny alalan\'ny lahatsary, famintinana novokarin\'ny AI, ary fanontaniana mifampiresaka. Sivana ny votoaty amin\'ny firenena.',
      
      // Blog
      'blog.title': 'Blog',
      'blog.subtitle': 'Vakio lahatsoratra blog mamporisika avy amin\'ny fiarahamonina. Sivana amin\'ny firenena mba hijery votoaty avy amin\'ny faritra manokana.',
      
      // Publications
      'publications.title': 'Famoahana',
      'publications.subtitle': 'Fidirana amin\'ny famoahana PDF miaraka amin\'ny famintinana novokarin\'ny AI. Sivana amin\'ny firenena mba hahitana votoaty mifandraika amin\'ny faritrao.',
      
      // Media
      'media.title': 'Foiben\'ny Haino Kristiana',
      'media.subtitle': 'Mijery lahatsary, mihaino mozika ary mifaly amin\'ny podcast. Sivana amin\'ny firenena mba hahitana votoaty avy amin\'ny faritra manokana.',
      
      // Directory
      'directory.title': 'Lisitra',
      'directory.subtitle': 'Votoaty lisitra ho avy...',
      
      // Projects
      'projects.title': 'Fampisehoana Tetikasa',
      'projects.subtitle': 'Zahao ny tetikasa sy ny hetsika avy amin\'ny fiarahamonina. Sivana amin\'ny firenena mba hijery tetikasa avy amin\'ny faritra manokana.',
      
      // Common
      'common.filterByNation': 'Sivana Amin\'ny Firenena',
      'common.allNations': 'Firenena Rehetra',
      'common.customNation': 'Firenena manokana...',
      'common.clear': 'Fafana',
      'common.showing': 'Aseho ny votoaty ho an\'ny',
      'common.loading': 'Ampidirina...',
      'common.back': 'Miverina',
      'common.backTo': 'Miverina amin\'ny',
      'common.by': 'nandika',
      'common.notFound': 'Tsy hita ny votoaty',
      'common.noContent': 'Tsy misy votoaty mbola misy.',
      'common.backToList': '← Miverina amin\'ny Lisitra',
      
      // Footer
      'footer.tagline': 'Tafaray amin\'ny finoana, miasa ho an\'ny Firenena. Sehetra nomerika voalohany mampiray ny mpandray anjara kristiana miady amin\'ny fanovana ara-panahy, ara-moraly ary ara-panjakana amin\'ny firenena.',
      'footer.community': 'Fiarahamonina',
      'footer.resources': 'Fanànana',
      'footer.about': 'Momba',
      'footer.rights': 'Zo rehetra voatokana.',
      'footer.designedBy': 'Nataon\'i',
      'footer.prayerRooms': 'Fivavahana',
      'footer.meetings': 'Fivoriana',
      'footer.worship': 'Fivavahana',
      'footer.learning': 'Fampianarana',
      'footer.blog': 'Blog',
      'footer.publications': 'Famoahana',
      'footer.media': 'Haino',
      'footer.directory': 'Lisitra',
      'footer.projects': 'Tetikasa',
      'footer.aboutUs': 'Momba Anay',
      
      // Contact Page
      'contact.title': 'Fifandraisana Aminay',
      'contact.subtitle': 'Manana fanontaniana momba ny asanay? Te-hiaraka aminay? Na te-hianatra bebe kokoa? Tianay ny hihaino anao. Mifandraisa aminay amin\'ny alalan\'ny fantsona iray amin\'ireo etsy ambany.',
      'contact.quickResponse': 'Valiny Haingana',
      'contact.multipleChannels': 'Fantsona Maro',
      'contact.contactInfo': 'Fampahalalana Fifandraisana',
      'contact.contactInfoDesc': 'Fidio ny fomba azo antoka indrindra mba hifandray aminay. Eto izahay mba hanampy sy hamaly ny fanontaniana rehetra momba ny iraka sy ny asanay.',
      'contact.emailUs': 'Mailaka',
      'contact.emailUsDesc': 'Alefaso hafatra aminay amin\'ny fotoana rehetra',
      'contact.callUs': 'Antsoy',
      'contact.callUsDesc': 'Miresaka mivantana amin\'ny ekipanay',
      'contact.visitUs': 'Mitsidika',
      'contact.visitUsDesc': 'Ny toerana misy ny birao foibenay',
      'contact.sendMessage': 'Alefaso Hafatra',
      'contact.sendMessageDesc': 'Fenoy ny taratasy etsy ambany ary hiverina aminao izahay ao anatin\'ny 24 ora. Ho an\'ny raharaha maika, azafady antsoy mivantana.',
      'contact.formName': 'Anarana Feno',
      'contact.formNamePlaceholder': 'Ny anaranao feno',
      'contact.formEmail': 'Adiresy Email',
      'contact.formEmailPlaceholder': 'ny@email.com',
      'contact.formSubject': 'Lohahevitra',
      'contact.formSubjectPlaceholder': 'Lohahevitra amin\'ny hafatrao',
      'contact.formMessage': 'Hafatra',
      'contact.formMessagePlaceholder': 'Ny hafatrao...',
      'contact.formSubmit': 'Alefa Hafatra',
      'contact.formSubmitting': 'Ampidirina...',
      'contact.formSuccess': 'Voarakitra ny hafatra! Hiverina aminao izahay ao anatin\'ny 24 ora.',
      'contact.formError': 'Diso ny fampidirana hafatra. Andramo indray azafady.',
      'contact.formRequired': '* Saha voatery. Hiverina aminao izahay ao anatin\'ny 24 ora.',
      'contact.findUs': 'Hitady Anay',
      'contact.mainOffice': 'Ny Birao Foibe',
      'contact.getDirections': 'Mahazo Torolalana',
      'contact.responseTimes': 'Fotoana Famaliana',
      'contact.generalInquiries': 'Fanontaniana Ankapobeny',
      'contact.generalInquiriesTime': 'Ao anatin\'ny 24 ora',
      'contact.partnershipInquiries': 'Fanontaniana Fiaraha-miasa',
      'contact.partnershipInquiriesTime': 'Ao anatin\'ny 72 ora',
      'contact.emergencyContact': 'Fifandraisana Maika',
      'contact.emergencyContactTime': 'Mivantana',
      
      // About Page
      'about.intro': 'Ny sehetra nomerika FPK – Fanavaozam-Pirenena Kristiana – dia toerana nomerika voalohany natao hanitarana, hanorina ary hanamafy ny hery natomboka tamin\'ny FPK amin\'ny fotoana lavalava. Manana tanjona ho fitaovana mampiraisina, miara-miasa ary stratejika, manompo ny mpandray anjara rehetra, mpandray anjara ary mpanohana rehetra miady amin\'ny fanovana ara-panahy, ara-moraly ary ara-panjakana amin\'ny firenena.',
      'about.mission': 'Ny Asa Anay',
      'about.missionDesc': 'Ny asa voalohany amin\'ny sehetra nomerika FPK dia ny mamorona rafitra nomerika maharitra izay:',
      'about.mission1': 'Hitazona ny fiaraha-miasa, ny fandrindrana ary ny fiaraha-miasa eo amin\'ny mpandray anjara FPK mihoatra ny fivoriana sy fivoriambe tsy ara-dalàna',
      'about.mission2': 'Hanorina ny fandraisana anjara miaraka amin\'ny fijery kristiana amin\'ny fanovana nasionaly',
      'about.mission3': 'Hampiroborobo ny fisainana, ny fampianarana, ny hetsika miaraka, ary ny fahafahana mamaly ny lohahevitra lehibe amin\'ny firenena',
      'about.missionEnd': 'Amin\'ny alalan\'ity platform ity, ny FPK dia maniry ho lasa foiben\'nomerika ho an\'ny fifanakalozana, ny fifampiresahana, ny fampianarana, ary ny fikambanana andraikitra.',
      'about.vision': 'Ny Fijery Anay',
      'about.visionDesc': 'Hampiroborobo ny fivoahan\'ny firenena vaovao, miorina amin\'ny soatoavina kristiana, ny andraikitra ara-panjakana, ny fahamarinana ara-moraly, ary ny fanompoana ny tombontsoa iraisana.',
      'about.visionEnd': 'Ity fijery ity dia ao anatin\'ny dinamika fanavaozana maharitra, izay ny finoana, ny fandraisana anjara ara-panjakana, ary ny hetsika miaraka dia mampifangaro mba hanorina hoavy feno fanantenana.',
      'about.governance': 'Fitantanana Voarindra sy Mampiditra',
      'about.governanceDesc': 'Ny sehetra nomerika FPK dia miorina amin\'ny fikambanana mazava sy mpandray anjara:',
      'about.circleZero': 'Ny Faribolana Zero',
      'about.circleZeroDesc': 'Vatana torolalana stratejika sy ara-panahy, manome antoka ny fijery, ny soatoavina, ary ny etika amin\'ny FPK',
      'about.coreTeam': 'Ny Ekipa Fototra',
      'about.coreTeamDesc': 'Ekipa miasa fototra tompon\'andraikitra amin\'ny fandrindrana ankapobeny, ny fitantanana platform, ary ny fanaraha-maso ny hetsika',
      'about.thematicLeaders': 'Ny Mpitari-dalana Thematika 10',
      'about.thematicLeadersDesc': 'Mpamora ny vondrona thematika, mpamokatra votoaty, ary mpampiroborobo ny tolo-kevitra sy hetsika',
      'about.regionalCommittees': 'Ny Komity FPK Eo Amin\'ny Faritra',
      'about.regionalCommitteesDesc': 'Mpikambana ara-tany tompon\'andraikitra amin\'ny fikambanana eo an-toerana, ny fanangonana valin-kevitra avy amin\'ny saha, ary ny fandaminana hetsika amin\'ny ambaratonga ara-tany',
      'about.platform': 'Sehetra Manompo Ny Hetsika',
      'about.platformDesc': 'Ny sehetra nomerika FPK dia manome fitaovana maoderina sy azo antoka ho an\'ny:',
      'about.platform1': 'Fiarahamonina sy Tambajotra',
      'about.platform1a': 'Fisoratana anarana sy profil ny mpikambana (mpandray anjara sy mpanohana)',
      'about.platform1b': 'Lisitra anatiny azo antoka',
      'about.platform1c': 'Fifandraisana amin\'ny alalan\'ny lohahevitra na faritra',
      'about.platform2': 'Fifandraisana Anatiny',
      'about.platform2a': 'Hafatra anatiny',
      'about.platform2b': 'Toerana resaka (foroma, vondrona lohahevitra, vondrona ara-tany)',
      'about.platform2c': 'Fandaminana fivoriana amin\'ny aterineto (videoconference)',
      'about.platform3': 'Vaovao sy Loharanom-bola',
      'about.platform3a': 'Vaovao FPK sy fanambarana ofisialy',
      'about.platform3b': 'Tranomboky nomerika (taratasy, tatitra, fanambarana, loharanom-bola FPK)',
      'about.platform3c': 'Kalandrie ny hetsika sy fivoriana',
      'about.platform4': 'Fampianarana sy Fanamafisana Ny Fahafahana',
      'about.platform4a': 'Moduly fampianarana amin\'ny aterineto (ara-panahy, fitarihana, zom-pirenena, fitantanana, sns.)',
      'about.platform4b': 'Webinaire sy fampianarana video',
      'about.platform4c': 'Toerana resaka aorian\'ny fampianarana',
      'about.platform5': 'Fandaminana sy Hetsika',
      'about.platform5a': 'Fitaovana fandrindrana ho an\'ny hetsika maika na laharam-pahamehana',
      'about.platform5b': 'Fikambanana haingana ny mpikambana amin\'ny alalan\'ny lohahevitra na faritra',
      'about.platform5c': 'Fanaraha-maso ny fikambanana sy hetsika natao',
      'about.platform6': 'Fitantanana sy Fandraisana Anjara',
      'about.platform6a': 'Fifampiresahana anatiny',
      'about.platform6b': 'Fikarohana sy taratasy toerana miaraka',
      'about.platform6c': 'Fandraisana anjara ny mpikambana (tolokevitra, fisainana, fampitandremana)',
      'about.future': 'Fomba Fijery Hoavy',
      'about.futureDesc': 'Natao ho fitaovana miovaova, ny sehetra nomerika FPK dia natao hokatra tsikelikely ho an\'ny vahoaka bebe kokoa, hifandray amin\'ny fiangonana, ny fikambanana mpiara-miasa, ary ny diaspora, ary hampiditra serivisy vaovao, anisan\'izany ny fampiharana finday sy ny tahiry amin\'ny fanambarana nasionaly lehibe.',
    },
  }
  
  return translations[lang] || translations.mg
}

